### ISSUE TITLE
There's major layout shift due to translation loading.

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/coreproject-v4-ui#124]
Proposal:

1. Wait the DOM until translations are loaded
2. Use Skeleton in place of texts

**Comment by baseplate-admin** [comment]
So what i am thinking is basically we set a flag variable (that defaults to `false`) and then do something like

```svelte
<!-- layout.svelte -->

{#if translation_is_loaded}
    {@render children()}
    
{:else}
     <!--titan Lottei-->
 {/if}
 ```

**Comment by moonlitgrace** [comment]
```svelte
{:else}
     <!--titan Lottei-->
 {/if}
```
Okay you mean some kinda mascot loading animation on middle?
yea also `i18n` provides a `$loading` store, we can use it as flag ig.

**Comment by moonlitgrace** [comment]
Seems like fixed on
 - https://github.com/baseplate-admin/coreproject-v4-ui/pull/177
 - https://github.com/baseplate-admin/coreproject-v4-ui/pull/180
