### ISSUE TITLE
Add colorthief to get gradient

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/coreproject-v4-ui#20]
We can use colorthief to get some gradient and construct them into a linear-gradient

**Comment by baseplate-admin** [comment]
https://github.com/coreproject-moe/CoreProject-Monorepo/blob/2511a842c3c4804d35ee92d6f3b491bd2d7c13fd/backend/django_core/static_src/components/page/anime/info/Index.svelte#L9

https://github.com/coreproject-moe/CoreProject-Monorepo/blob/2511a842c3c4804d35ee92d6f3b491bd2d7c13fd/backend/django_core/static_src/components/page/anime/info/Index.svelte#L43-L71

Most likely we want to draw image on a canvas

**Comment by moonlitgrace** [comment]
@baseplate-admin are you there? why arent you responding on tg?

**Comment by baseplate-admin** [comment]
![Screenshot_20240915_234541_Telegram.jpg](https://github.com/user-attachments/assets/1e265c90-c603-4971-b1d3-bb09506cd845)

What do u mean?

**Comment by moonlitgrace** [comment]
![2024-09-15_23-46](https://github.com/user-attachments/assets/f698fce9-aff2-4c79-b0c0-8ebb1b9e8dc8)

WTF :\

**Comment by baseplate-admin** [comment]
@moonlitgrace i think the damn govt again blocked telegram.

So how do you want to communicate?

**Comment by baseplate-admin** [comment]
Btw @moonlitgrace fun fact, i can talk to all my friends over on this side of the pond. You sure its not something local?
