### ISSUE TITLE
Translations not loading on specific url pattern

### ISSUE THREAD

**Issue by moonlitgrace** [baseplate-admin/coreproject-v4-ui#315]
eg: not working pattern: `http://localhost:5174/anime/1/episode/1`
working pattern: `http://localhost:5174/anime/mal/1/episode/1`

`mal` can be anything from `anime` url params matcher

![2024-07-31_20-51](https://github.com/user-attachments/assets/5157747a-f2b0-40d2-81db-34e2b22ba983)

**Comment by baseplate-admin** [comment]
I solved this before. Lets have a look at this
