### ISSUE TITLE
Ad i18n and l10n

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/coreproject-v4-ui#44]
[`sveltekit-i18n`](https://github.com/sveltekit-i18n/lib)

I can offer support for :

* English
* Bangla
* Japanese 
* Hindi
* Urdu

**Comment by tokitouq** [comment]
> I can offer support for :

OH you're taking this?
okay lemme assign this to you then

**Comment by baseplate-admin** [comment]
Add the boilerplates and i will look into the translation part

**Comment by tokitouq** [comment]
https://github.com/sveltekit-i18n/lib/issues/161
@baseplate-admin could you update vercel config? otherwise deployments will be failing :(

**Comment by baseplate-admin** [comment]
Fixed
